
from flask import Flask, request, send_from_directory
from flask_reloaded import Reloaded
from flask_debugtoolbar import DebugToolbarExtension
app = Flask(__name__)
app.debug = True
app.config['SECRET_KEY'] = 'flskjsdf994994304023.,m.,mvxclds'
app.config['DEBUG_TB_PANELS'] = (
    # ...
    'flask_reloaded.panels.ReloadedDebugPanel',
)
DebugToolbarExtension(app)
reloaded = Reloaded(app)

@app.route('/')
def hello_world():
    return 'Hello, World!'

from flask import render_template

@app.route('/hello/')
@app.route('/hello/<name>')
def hello(name=None):
    return render_template('hello.html', name=name)

import pprint
import owlready
from owlready import *
onto_path.append(os.path.dirname(__file__))
onto = load_ontology_from_file("floss-events.owl")

#
#Property: EventWho,
#type:              Agent,
#                   Role

#Prop:     EventWhat,
# to what :
# PhysicalThing
# AbstractDocument
# via UserInterface
# DataResource
# to what that is formatted
# Dataformat
#type              Model,
# Event :

#Prop:     EventWhere
#            PhysicalLocation
#            DataResource

#Prop:     EventWhen,
#type:        Event,

# How
#Prop          EventWhy,
# cause, purpose : Model

#    Visitor declares interest in hearing a talk on topic X
#                 EventExpressesInterestInLearning,

# 'classes': [CodeOfConduct,
#              Continent,
#              ProjectEvent,
#              County,
#              TimeZone,
#              Bus,
#              EmailEvent,
#              JavaScriptCodingRole,
#              AdvertiserRole,
#              State,
#              Media,
#              Past,
#              Planned,
#              Student,
#              Country,
#              ArchiverRole,
#              OpenId,
#              VersionLabel,
#              PrintedBanner,
#              MembershipDataDocument,
#              School,
#              Current,
#              Policy,
#              Commit,
#              Image,
#              OAuth,
#              Role,
#              Workshop,
#              TwitterProfilePage,
#              ConferenceTrack,
#              VolunteerRole,
#              ScheduledTask,
#              Tutorial,
#              Hallway,
#              Identifier,
#              CallForTestamonials,
#              CPlusPlusModel,
#              ReleaseSystem,
#              LogisticsRole,
#              SkillsManagerRole,
#              Point,
#              XMLDataModel,
#              EventSchedule,
#              IRCChannel,
#              GovernmentAgency,
#              EducationalEntity,
#              Building,
#              Disclousure,
#              NonProfitOrganization,
#              PolicyMakingRole,
#              FreeAndOpenSourcePolicy,
#              StateModel,
#              CSSCodingRole,
#              LegalEntity,
#              InvoiceItem,
#              CityMap,
#              GooglePlusPage,
#              Authentification,
#              Talk,
#              Process,
#              MarkdownModel,
#              DataContributorRole,
#              SoftwareTestingRole,
#              TrainerRole,
#              BusPlan,
#              Symbol,
#              Audio,
#              Firewall,
#              Banner,
#              CallForSponsors,
#              ForumPost,
#              AbstractDocument,
#              Supported,
#              MediaWikiPage,
#              DeveloperList,
#              StudentRole,
#              Stickers,
#              Floor,
#              MailingListEvent,
#              CommercialCompany,
#              SoftwareRole,
#              DocumentationWriterRole,
#              StandardDataFormat,
#              Campus,
#              Developer,
#              DataResource,
#              DataModel,
#              AbstractMembershipDocument,
#              ModellingActivity,
#              DirectionSigns,
#              VotingEvent,
#              TransportationAgency,
#              TwitterHandle,
#              FourSquarePage,
#              Path,
#              WikiSystem,
#              Website,
#              BusCompany,
#              Train,
#              FundingReviewRole,
#              MercurialRepository,
#              WebsiteDataModel,


#              Airline,
#              Society,
#              MatrixRoom,
#              YAMLModel,
#              OWLModel,
#              Car,
#              Name,
#              CommunicationVenue,
#              ProjectMeeting,
#              BusinessIncubator,
#              Community,
#              ForumThread,
#              TopicName,
#              ProductAwareness,
#              Group,
#              TalkSubmissionEvent,
#              AdvertisingAgency,
#              Room,
#              CallForExhibits,
#              BrandRecognition,
#              InConflict,
#              Makerspace,
#              Teeshirt,
#              BugReportingRole,
#              Accessibility,
#              ProductCategory,
#              RecruiterCompany,
#              TaxiCompany,
#              GroupMembershipRole,
#              MembershipRecruiterRole,
#              OpenDataFormat,
#              Vehicle,
#              Payment,
#              Law,
#              BazaarRepository,
#              SearchActivity,
#              TrackerItemThread,
#              DatabaseServer,
#              CSVModel,
#              IssueTracker,
#              Offer,

#              ContributorRecruiterRole,
#              URL,
#              MailingListThread,
#              EventStateModel,
#              TelegramChannel,
#              EventSeries,
#              SlackChannel,
#              DigitalSignature,
#              RecruiterRole,
#              UMLModel,
#              SubversionRepository,
#              EventBriteDataModel,
#              PrintedTicket,
#              CallForParticipation,
#              Airplane,
#              CallForVenues,
#              TrainCompany,
#              DeveloperRole,
#              Invoice,
#              Merchandise,
#              Handbook,
#              JSONDataModel,
#              CheckInList,
#              FamilyName,
#              FacebookDataModel,
#              Swag,
#              Video,
#              MetaDataContributorRole,
#              MailingList,
#              MentalResource,
#              HTMLDataModel,
#              MembershipJoinEvent,
#              Dataformat,
#              LabelingEvent,
#              Trademark,
#              EventState,
#              OfflineEvent,
#              TwitterDataModel,
#              DVD,
#              FacebookPage,
#              GitRepository,
#              LearningEvent,
#              SponsoringRole,
#              FacebookPost,
#              PhysicalDocument,
#              CallFor,
#              FreeSoftwareProject,

#              SQLDataModel,
#              DiscussionThread,
#              SchoolDirectorRole,
#              CallForPapers,
#              BoothSession,
#              TwitterThread,
#              Webpage,
#              InteropereableDataFormat,
#              PhysicalLocation,
#              FundraisingRole,
#              WikidataPage,
#              SelectionActivity,
#              Brand,
#              Neighbourhood,
#              License,
#              YelpPage,
#              Activity,
#              ApplicationForJoining,
#              OpenDataPolicy,
#              EducationalDegree,
#              CDRom,
#              WebUserThrottle,
#              Email,
#              SpeakerAssistantRole,
#              SoftwareRepository,
#              City,
#              Map,
#              PhysicalThing,
#              Rights,
#              CV,
#              WebQualityOfService,
#              Statutes,
#              EventManagementRole,
#              SchoolTeacherRole,
#              SpeakerRole,
#              WebClient,
#              WebResource,
#              Commitment,
#              SkillsTestEvent,
#              KnowledgeContributorRole,
#              WikipediaPage,
#              BrowseActivity,
#              CommunityManagerRole,
#              TalkEvent,
#              PictureContributorRole,
#              OrganizationEntity,
#              Webserver,
#              FacebookResource,
#              Task,
#              CategorizationActivity,
#              WebBanner,
#              OpenStreetmapNode,
#              WikiPage,
#              EmailMarketingRole,
#              Certification,
#              Proposed,
#              Conference,
#              OnlineEvent,
#              Poster,
#              SoftwareCompany,
#              Hotel,
#              RegistrationPeriod,
#              ComputerMemoryModel,
#              UserInterface,
#              Tweet,
#              TalkCommentEvent,
#              CreativeCommonsContributorRole,
#              Hostel,
#              CoderRole,
#              House,
#              EventAttendees,
#              Book,
#              InPreparation,
#              Person,
#              UserRole,
#              CallForDemos,
#              FloorPlan,
#              CallForVideos,
#              CommunicationsEvent,
#              MarketingAgency,
#              Documentation,
#              Demonstration],
#  'imported_ontologies': [],
#  'instances': [Mozilla,
#                Document_Foundation,
#                OpenStreetmap,
#                Wikipedia,
#                Fedora_Project,
#                bus_1],
#  'loaded': False,
#  'name': 'floss-events',
#  'properties': [EventMeetupProposal,
#                 wants,
#                 EventWhatRelatedMedia,
#                 DoNoTrack,
#                 EventDPWhereLat,
#                 EventResourceAvailable,
#                 EventToWhom,
#                 needs,
#                 EventTravelResource,
#                 EventSpeakerProposal,

#                 EventVenueAvailableTime,
#                 EventDPToWho,

#                 EventTalkCommentPost,
#                 EventResourceProposal,
#                 EventOnTopic,
#                 EventSharingEvent,
#                 SocialLink,
#                 EventFavoriteEvent,
#                 EventSpeakerNotAvailableTime,
#                 EventResourceConsumer,
#                 EventDPWhen,
#                 EventDPHow,
#                 EventSponsorProposal,
#                 EventWhoContact,
#                 EventResourceNeeded,
#                 EventTalkMediaPost,
#                 LinkedInLink,
#                 EventWherePaymentIsMade,
#                 EventWhatIndirectObject,

#                 EventUserStudent,
#                 EventProposesTalkOnTopic,
#                 EventVenueNotAvailableTime,
#                 EventTalkQuestionPost,
#                 EventHow,
#                 EventVenue,
#                 EventTalkCodePost,
#                 EventSponsorGovernment,
#                 EventDPWhy,
#                 EventWhoContactRepresentative,
#                 EventContactPhone,
#                 EventSpeakerAvailableTime,
#                 EventLinkToAbstractOnTalk,
#                 EventVenueProposal,
#                 FacebookLink,



#                 EventExpressesExpertiseInTopic,
#                 EventWhatDirectObject,
#                 EventWhoContactApprover,
#                 EventTalkSocialPost,
#                 EventWhenFrom,
#                 EventRatingEvent,
#                 EventVenueAvailablePlace,
#                 EventRankingEvent,
#                 EventSponsor,
#                 EventUser,
#                 EventTalkIssuePost,
#                 WhoAuthorisesPayment,
#                 TwitterLink,
#                 EventResourceNotAvailableTime,
#                 EventResourceAvailableTime,
#                 EventResourceProvider,
#                 EventTalkBlogPost,
#                 EventDataProperty,
#                 EventWhatRelatedEvent,
#                 EventSpeakerAvailablePlace,
#                 EventExpressesInterestInSpeaking,
#                 EventDPWhere,
#                 EventDPWhereLon,
#                 EventDPWhat,
#                 EventDPWho,
#                 EventAccomodationProposal,
#                 EventResourceCommitted,
#                 DifficultyLevel,
#                 EventInviteSpeaker,
#                 EventSponsorCompany,
#                 EventTravelProposal,
#                 EventTopicProposal,
#                 EventProperty,
#                 EventWhenTo,
#                 EventWhoAttendee,
#                 EventWhomRecievesPayment,
#                 EventScheduleVote,
#                 EventScheduleRequirements,
#                 EventScheduleProposal,
#                 LanyardLink]}
 
@app.route('/onto/')
def info():
    b = onto.Bus()
    #pprint.pprint(b._instance_to_n3())
    #pprint.pprint(b._instance_to_owl())


    return "<html><body><h1>Hello</h1><pre>" + pprint.pformat(onto.__dict__) + "</pre><pre>"+ pprint.pformat(dir(onto)) + "</pre><pre>"+ pprint.pformat(b) + "</pre><pre>"+ pprint.pformat(dir(b)) + "</pre><pre>"+ pprint.pformat(b.__dict__)+"</body></html>"

if __name__ == "__main__":
    app.run(debug=True)
